import type { JobRecord } from "./types";

const now = Date.now();
const hoursAgo = (hours: number) => new Date(now - hours * 3_600_000).toISOString();

export const demoJobs: JobRecord[] = [
  { id: "demo-1", source: "Greenhouse", sourceJobId: "gh-1024", canonicalUrl: "https://jobs.example.com/atlas/staff-product-engineer", title: "Staff Product Engineer", company: "Atlas Labs", location: "Bengaluru, Karnataka", description: "Lead product engineering for the systems that help modern Indian businesses grow. You will partner with design and data to ship thoughtful, reliable experiences.", employmentType: "Full-time", remote: false, salaryMin: 3200000, salaryMax: 4800000, salaryCurrency: "INR", postedAt: hoursAgo(3), firstSeenAt: hoursAgo(3), lastSeenAt: hoursAgo(3), contentHash: "demo-hash-1", isActive: true },
  { id: "demo-2", source: "Lever", sourceJobId: "lv-882", canonicalUrl: "https://jobs.example.com/meridian/senior-backend-engineer", title: "Senior Backend Engineer", company: "Meridian Finance", location: "Remote, India", description: "Build resilient APIs and data products for a fast-moving fintech team. Experience with TypeScript, Postgres, and event-driven systems is useful.", employmentType: "Full-time", remote: true, salaryMin: 2600000, salaryMax: 4000000, salaryCurrency: "INR", postedAt: hoursAgo(9), firstSeenAt: hoursAgo(9), lastSeenAt: hoursAgo(9), contentHash: "demo-hash-2", isActive: true },
  { id: "demo-3", source: "Ashby", sourceJobId: "ash-441", canonicalUrl: "https://jobs.example.com/bright/brand-designer", title: "Brand Designer", company: "Bright Commerce", location: "Mumbai, Maharashtra", description: "Shape the brand language for a new generation of commerce. Bring a sharp eye for systems, storytelling, and detail.", employmentType: "Full-time", remote: false, salaryMin: null, salaryMax: null, salaryCurrency: null, postedAt: hoursAgo(22), firstSeenAt: hoursAgo(22), lastSeenAt: hoursAgo(22), contentHash: "demo-hash-3", isActive: true },
  { id: "demo-4", source: "Apify", sourceJobId: "ap-109", canonicalUrl: "https://jobs.example.com/terracotta/data-analyst", title: "Data Analyst, Growth", company: "Terracotta", location: "Delhi NCR · Hybrid", description: "Turn customer and marketplace data into clear decisions for our growth teams. SQL fluency and strong communication matter most.", employmentType: "Contract", remote: false, salaryMin: 1200000, salaryMax: 1800000, salaryCurrency: "INR", postedAt: hoursAgo(31), firstSeenAt: hoursAgo(31), lastSeenAt: hoursAgo(31), contentHash: "demo-hash-4", isActive: true },
  { id: "demo-5", source: "Greenhouse", sourceJobId: "gh-777", canonicalUrl: "https://jobs.example.com/kite/mobile-engineer", title: "Mobile Engineer, Android", company: "Kite Health", location: "Hyderabad, Telangana", description: "Make healthcare more accessible through a dependable Android experience used by millions of people across India.", employmentType: "Full-time", remote: false, salaryMin: 1800000, salaryMax: 2800000, salaryCurrency: "INR", postedAt: hoursAgo(48), firstSeenAt: hoursAgo(48), lastSeenAt: hoursAgo(48), contentHash: "demo-hash-5", isActive: true },
  { id: "demo-6", source: "Lever", sourceJobId: "lv-103", canonicalUrl: "https://jobs.example.com/fieldnote/product-manager", title: "Product Manager, Platform", company: "Fieldnote", location: "Remote, India", description: "Own the platform roadmap and make complex workflows feel simple for teams building the future of work.", employmentType: "Full-time", remote: true, salaryMin: 2200000, salaryMax: 3400000, salaryCurrency: "INR", postedAt: hoursAgo(56), firstSeenAt: hoursAgo(56), lastSeenAt: hoursAgo(56), contentHash: "demo-hash-6", isActive: true },
  { id: "demo-7", source: "Ashby", sourceJobId: "ash-875", canonicalUrl: "https://jobs.example.com/monsoon/software-intern", title: "Software Engineering Intern", company: "Monsoon AI", location: "Pune, Maharashtra", description: "Join a small applied AI team and ship production features with experienced engineers. This is a paid internship for 2026 graduates.", employmentType: "Internship", remote: false, salaryMin: 300000, salaryMax: 500000, salaryCurrency: "INR", postedAt: hoursAgo(72), firstSeenAt: hoursAgo(72), lastSeenAt: hoursAgo(72), contentHash: "demo-hash-7", isActive: true },
  { id: "demo-8", source: "Apify", sourceJobId: "ap-226", canonicalUrl: "https://jobs.example.com/zeroq/devops-engineer", title: "DevOps Engineer", company: "ZeroQ", location: "Chennai, Tamil Nadu · Hybrid", description: "Build the deployment platform and observability practices that keep our customer-facing services fast and available.", employmentType: "Full-time", remote: false, salaryMin: 1600000, salaryMax: 2600000, salaryCurrency: "INR", postedAt: hoursAgo(94), firstSeenAt: hoursAgo(94), lastSeenAt: hoursAgo(94), contentHash: "demo-hash-8", isActive: true },
];
