import { normalizeJob } from "./normalize";

export type SourceAdapterConfig = { board?: string; apiKey?: string; country?: string; actorId?: string };
export interface SourceAdapter { name: string; fetchListings(config: SourceAdapterConfig): Promise<unknown[]>; }

async function json(url: string, init?: RequestInit) {
  const response = await fetch(url, { ...init, headers: { Accept: "application/json", ...init?.headers } });
  if (!response.ok) throw new Error(String(response.status) + " from " + url);
  return response.json();
}
function record(value: unknown): Record<string, unknown> { return typeof value === "object" && value !== null ? value as Record<string, unknown> : {}; }
function stringValue(value: unknown) { return typeof value === "string" || typeof value === "number" ? String(value) : undefined; }
export const greenhouseAdapter: SourceAdapter = { name: "greenhouse", async fetchListings({ board }) { if (!board) return []; const result = await json("https://boards-api.greenhouse.io/v1/boards/" + encodeURIComponent(board) + "/jobs?content=true") as { jobs?: unknown[] }; return (result.jobs ?? []).map((raw) => { const item = record(raw); return normalizeJob({ sourceJobId: stringValue(item.id), title: stringValue(item.title), company: stringValue(record(item.company).name), location: stringValue(record(item.location).name), description: stringValue(item.content), url: stringValue(item.absolute_url), employmentType: stringValue(record(item.metadata).employment_type) }, "Greenhouse"); }); } };
export const leverAdapter: SourceAdapter = { name: "lever", async fetchListings({ board }) { if (!board) return []; const result = await json("https://api.lever.co/v0/postings/" + encodeURIComponent(board) + "?mode=json") as unknown; return (Array.isArray(result) ? result : []).map((raw) => { const item = record(raw); return normalizeJob({ sourceJobId: stringValue(item.id), title: stringValue(item.text), company: board, location: stringValue(record(item.categories).location), description: stringValue(item.descriptionPlain ?? item.description), url: stringValue(item.hostedUrl ?? item.applyUrl), employmentType: stringValue(record(item.categories).commitment), remote: item.workplaceType === "remote" }, "Lever"); }); } };
export const ashbyAdapter: SourceAdapter = { name: "ashby", async fetchListings({ board }) { if (!board) return []; const result = await json("https://api.ashbyhq.com/posting-api/job-board/" + encodeURIComponent(board)) as { jobs?: unknown[] }; return (result.jobs ?? []).map((raw) => { const item = record(raw); return normalizeJob({ sourceJobId: stringValue(item.id), title: stringValue(item.title), company: board, location: stringValue(item.location), description: stringValue(item.descriptionPlain ?? item.descriptionHtml ?? item.description), url: stringValue(item.jobUrl ?? item.applyUrl), employmentType: stringValue(item.employmentType), remote: item.isRemote }, "Ashby"); }); } };
export const adzunaAdapter: SourceAdapter = { name: "adzuna", async fetchListings({ apiKey, country = "in" }) { const appId = process.env.ADZUNA_APP_ID; if (!appId || !apiKey) return []; const result = await json("https://api.adzuna.com/v1/api/jobs/" + country + "/search/1?app_id=" + encodeURIComponent(appId) + "&app_key=" + encodeURIComponent(apiKey) + "&results_per_page=50&what=technology") as { results?: unknown[] }; return (result.results ?? []).map((raw) => { const item = record(raw); return normalizeJob({ sourceJobId: stringValue(item.id), title: stringValue(item.title), company: stringValue(record(item.company).display_name), location: stringValue(record(item.location).display_name), description: stringValue(item.description), url: stringValue(item.redirect_url), employmentType: stringValue(item.contract_type), salaryMin: typeof item.salary_min === "number" ? item.salary_min : undefined, salaryMax: typeof item.salary_max === "number" ? item.salary_max : undefined, postedAt: stringValue(item.created) }, "Adzuna"); }); } };
export const apifyAdapter: SourceAdapter = { name: "apify", async fetchListings({ actorId }) { if (!actorId) return []; const token = process.env.APIFY_TOKEN; if (!token) return []; const run = await json("https://api.apify.com/v2/acts/" + encodeURIComponent(actorId) + "/runs?token=" + encodeURIComponent(token), { method: "POST", body: JSON.stringify({}) }) as { defaultDatasetId?: string }; if (!run.defaultDatasetId) return []; return json("https://api.apify.com/v2/datasets/" + encodeURIComponent(run.defaultDatasetId) + "/items?token=" + encodeURIComponent(token) + "&clean=true") as Promise<unknown[]>; } };
export const sourceAdapters = { greenhouse: greenhouseAdapter, lever: leverAdapter, ashby: ashbyAdapter, adzuna: adzunaAdapter, apify: apifyAdapter };
